### ISSUE TITLE
gradle update corrupts git repository

### ISSUE THREAD

**Issue by anderskristian** [vlingo/vlingo-platform#9]
According to README.md the correct procedure is to run
```
./gradlew

```
to get a full set of vlingo. 
Yes it does ... BUT BUT BUT BUT .. it also commits a change to my local git version in each module.
I find this wrong !!!

so each time I have made **git pull** in all directories the system commits for me in each directory

I suggest to make a script that simple runs the list of **git pull** - and remove all the other magic build.gradle contains !!! 

I have to go through each repo and make a clone - and the replace .git in the fresh module with the corrupted .git in the module

By the way version 1.2.3 was forgotten in **platform**

**Comment by Florian-Schoenherr** [comment]
See #11 - the gradle stuff was old.
I will close this, it seems resolved.
You can comment here if there's still a problem and we'll reopen!
